name: ffmpeg
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
    
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Preparing Linux Environment
      run: sudo apt-get update
    - name: Install ffmpeg
      run: sudo apt-get install ffmpeg -y

- name: download file
      run: bash wget.sh
      env:
        link: ${{ secrets.link }}
    
- name: Mulai encode
    #  if: ${{ failure() }}
      run: bash run.sh
      env:
        input: ${{ secrets.input }}
       
